### ISSUE TITLE
Running the extension in dev environment fails on first run

### ISSUE THREAD

**Issue by dandua98** [microsoft/WebTemplateStudio#392]
**Reproduction steps:**

- Open *src/extension* in VSCode and use F5 to launch in dev mode.
- Launch Web Template Studio using `Cmd+Shift+P` and `Web Template Studio: Launch`. This would fail on first run with an error `Could not sync template repository`. 
- Running the last step again would work after

**System Info:**

Mac mini (late 2014) running *macOS Mojave version 10.14.4*
Processor 2.6 GHz Intel Core i5
Memory 8 GB 1600 MHz DDR3
Graphics Intel Iris 1536 MB

**Comment by AdalWay** [comment]
I just had this problem today, I'm trying to open the template studio, I'm using ubuntu 19.04.

**Comment by crutkas** [comment]
@adalway, what version of code are you on?

**Comment by AdalWay** [comment]
@crutkas  this is the version 1.33.1

**Comment by AdalWay** [comment]
I just updated visual code and still the same error.

[2019-05-16, 5:04:50 p.m.][EXTENSION] Launched
[2019-05-16, 5:05:04 p.m.][EXTENSION] Error: Could not sync to template repository

**Comment by crutkas** [comment]
Ok, we will look at this. We will try to repro it. Believe in VS code the output should have logs, can you see if there are any?

**Comment by AdalWay** [comment]
@crutkas That was the output... I have not been able to open the Web Template Studio, I guess that in Linux is not working for now

**Comment by rakkarage** [comment]
same, ubuntu, output

[2019-05-17, 9:17:32 a.m.][EXTENSION] Launched
[2019-05-17, 9:17:45 a.m.][EXTENSION] Error: Could not sync to template repository

**Comment by crutkas** [comment]
We figured out the issue, thanks everyone for working with us.  we have to do signed builds for publishing to marketplace and looks like for some reason, it works on the mac and windows but fails for one file in the linux build to get signed.

we're proactively working on solving this.

**Comment by crutkas** [comment]
So verified with code signing team, the signing process is dropping files.  Extracting the source package shows 6195 files, but the signed package only has 5877

**Comment by crutkas** [comment]
I also do believe this is a different issue than the item posted here.  same outcome but based on age, that may have been resolved where this is due to a new process (signing the build)

@sibille is there some way we can add a test to verify extraction/install or maybe the same # of files to catch this before deployment

**Comment by sibille** [comment]
we can add a step in the build that verifies file number before and after signing

**Comment by FDiskas** [comment]
Same error. I just dwnloaded plugin on fresh pc and fresh VSCode :interrobang:
```Version: 1.34.0
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:55:35.507Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-30deepin-generic
```

**Comment by crutkas** [comment]
There is a known issue with our Linux Build due to code signing. We are proactively working in fixing this.

**Comment by sibille** [comment]
Just published version 0.0.1914003, which fixes this, if anybody still encounters this issue, please reopen!

**Comment by dzg** [comment]
On 0.0.1914003, same issue....

Action: Sync-Engine
Error type: Error
Error Message: Could not sync to template repository

Version: 0.0.1914003
OS: darwin
VS Code Version: 1.34.0

<details>
<summary>Call Stack</summary>

```
LaunchExperience.<anonymous> (/Users/<user>/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.0.1914003/out/launchExperience.js:39:23)
Generator.next (<anonymous>)
fulfilled (/Users/dang/.vscode/extensions/wasteamaccount.webtemplatestudio-dev-nightly-0.0.1914003/out/launchExperience.js:4:58)
```

</details>
